# Configure development environment

server:
  port: 80

# Spring configuration
spring:
  datasource:
    initialize: true
    name: wisper
    host: localhost
    port: 3306
    url: jdbc:mysql://localhost:3306/wisper?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_USERNAME:wisper}
    password: ${MYSQL_PASSWORD:wisper}
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    connection-timeout: 3000
    max-active: 200
    max-idle: 20
    min-idle: 10
    max-wait: 3000
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    initial-size: 10
  mail:
    host: smtp.ym.163.com
    name: jira@wancloud.io
    pwd: NklaS2RuRjNyZw==
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Wisper
wisper:
  task:
    cron: ${TASK_CRON:0 0 10 * * ?}
  mail:
    from: jira@wancloud.io
    targets: ${MAIL_TARGETS}

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework:
      data: ERROR
      web: ERROR
    io.wancloud: ERROR
    jdbc.core.JdbcTemplate: ERROR
  file: logs/wisper.log
